package com.tmb.enums;

public enum ConfigProperties {

    URL,
    BROWSER,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOTS,
    FAILEDSTEPSCREENSHOTS,
    SKIPPEDSTEPSCREENSHOTS,
    RETRYFAILEDTESTS,
    RUNMODE,
    SENDRESULTTOELK,
    SELENIUMGRIDURL,
    ELKURL

}
